version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: lumi_energy-bills-backend
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - DATABASE_URL=postgresql://postgres.oavzebovqvpssjflhriy:Tq6nCCg5q6yLtFlB@aws-0-us-east-2.pooler.supabase.com:6543/energy_bills
      - DATABASE_URL_LOCAL=postgresql://postgres.oavzebovqvpssjflhriy:Tq6nCCg5q6yLtFlB@aws-0-us-east-2.pooler.supabase.com:6543/energy_bills
      - FATURAS_FOLDER_PATH=./Faturas
    volumes:
      - ./back-end:/app
      - /app/node_modules
      - /app/dist
    command: yarn start:prod
    networks:
      - app-network
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: lumi_energy-bills-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=https://lumi-energy-bills-app.onrender.com
      - REACT_APP_ENV=development
      - REACT_APP_ENABLE_MOCK_DATA=false
      - GENERATE_SOURCEMAP=false
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front-end:/app
    command: npm start
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: lumi_energy-bills-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: energy_bills
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres_data:
