version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: lumi_energy-bills-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: energy_bills
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumi_energy-bills-api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://admin:admin@lumi_energy-bills-postgres:5432/energy_bills
      FATURAS_FOLDER_PATH: /app/faturas
    volumes:
      - .:/app
      - /app/node_modules
      - ./faturas:/app/faturas
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    name: lumi_energy-bills-postgres-data
